export const sources = [
    {   id: 0,
        title: "988 Suicide & Crisis Lifeline",
        description: "The 988 Lifeline provides 24/7, free and confidential support for people in distress, prevention and crisis resources for you or your loved ones, and best practices for professionals in the United States.",
        link: "https://988lifeline.org/",
        everyone: false,
        diagnoses: false,
        daily: false,
        crisis: true,
        practice: "organized",
        icon: "ChatLogo"
    },
    { 
        id: 4,
        title: "Signs and Symptoms of Mental Illnesses (NAMI)",
        description: "Understanding the signs and symptoms of commom mental illnesses.",
        link: "https://www.nami.org/About-Mental-Illness/Warning-Signs-and-Symptoms",
        everyone: false,
        diagnoses: true,
        daily: false,
        crisis: false,
        practice: "organized",
        icon: "BookLogo"
    },
    {
        id: 1,
        title: "About Mental Health (CDC)",
        description: "Learn the basics of mental health.",
        link: "https://www.cdc.gov/mentalhealth/learn/index.htm",
        everyone: true,
        diagnoses: true,
        daily: false,
        crisis: false,
        practice: "organized",
        icon: "BookLogo"
    },
    { 
        id: 2,
        title: "Therapist Finder (Psychology Today)",
        description: "Find detailed listings for mental health professionals in your area.",
        link: "https://www.psychologytoday.com/us/therapists",
        everyone: true,
        diagnoses: true,
        daily: true,
        crisis: false,
        practice: "organized",
        icon: "HealthLogo"
    },
    { 
        id: 3,
        title: "Utah mental health & substance use resources",
        description: "Public mental health resources local to Utah, sorted by county.",
        link: "https://mihp.utah.gov/maternal-resource-guide-utah/mental-health-substance-use",
        everyone: false,
        diagnoses: true,
        daily: true,
        crisis: true,
        practice: "organized",
        icon: "HealthLogo"
    },
    { 
        id: 5,
        title: "Supporting Mental Health in The Workplace (NAMI)",
        description: "Learn how to navigate, discuss, and thrive with mental health disorders in the workplace.",
        link: "https://www.nami.org/Blogs/NAMI-Blog/December-2022/Supporting-Mental-Health-in-The-Workplace",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "organized",
        icon: "BookLogo"
    },
    { 
        id: 6,
        title: "National Support Groups (MHA)",
        description: "National information on mental health support groups.",
        link: "https://www.mhanational.org/find-support-groups",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "organized",
        icon: "ChatLogo"
    },
    { 
        id: 18,
        title: "Support Groups in Utah (Psychology Today)",
        description: "Support groups local to Utah.",
        link: "https://www.psychologytoday.com/us/groups/utah",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: true,
        practice: "organized",
        icon: "ChatLogo"
    },
    { 
        id: 7,
        title: "Mental Health Medications (NIH)",
        description: "Information on common medications used in mental health treatment.",
        link: "https://www.nimh.nih.gov/health/topics/mental-health-medications",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "organized",
        icon: "HealthLogo"
    },
    { 
        id: 8,
        title: "Best Mental Health Apps of 2024 (CNET)",
        description: "These modern mental health apps may help you manage anxiety, depression and other problems.",
        link: "https://www.cnet.com/health/mental/7-best-mental-health-apps-to-start-using-today/",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "personal",
        icon: "PhoneLogo"
    },
    { 
        id: 9,
        title: "Managing Phone Time",
        description: "These modern mental health apps may help you manage anxiety, depression and other problems.",
        link: "https://fortune.com/well/2023/03/03/healthier-habits-phone-screen-time-technology/",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "personal",
        icon: "PhoneLogo"
    },
    { 
        id: 10,
        title: "Caring for Your Mental Health (NIH)",
        description: "Learn how to care for your mental health, regardless of diagnosis.",
        link: "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "personal",
        icon: "AccountLogo"
    },
    { 
        id: 11,
        title: "11 tips for coping with an anxiety disorder",
        description: "Tips on mental health management specific to anxiety disorders.",
        link: "https://www.mayoclinichealthsystem.org/hometown-health/speaking-of-health/11-tips-for-coping-with-an-anxiety-disorder",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "personal",
        icon: "AccountLogo"
    },
    { 
        id: 12,
        title: "National Resources for Immediate Response",
        description: "National resources for those in a mental health crisis.",
        link: "https://mhanational.org/crisisresources",
        everyone: false,
        diagnoses: false,
        daily: false,
        crisis: true,
        practice: "organized",
        icon: "HealthLogo"
    },
    { 
        id: 13,
        title: "25 best mental health books to read in 2024",
        description: "Book recommendations for those looking to understand and care for their mental health.",
        link: "https://www.panmacmillan.com/blogs/lifestyle-wellbeing/best-mental-health-books",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "personal",
        icon: "ReadingLogo"
    },
    { 
        id: 14,
        title: "8 Best Tools to Optimize your Daily Schedule",
        description: "Tools for being more productive in day to day life.",
        link: "https://www.supermonitoring.com/blog/tools-to-optimize-daily-schedule/",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "personal",
        icon: "CalendarLogo"
    },
    { 
        id: 15,
        title: "10 Best ADHD Organization Tools for Adults in 2024",
        description: "Daily productivity and organizational tools designed for those with ADHD.",
        link: "https://clickup.com/blog/adhd-organization-tools/",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "personal",
        icon: "CalendarLogo"
    },
    { 
        id: 15,
        title: "The Best Books on Habit Building",
        description: "Book recommendations for those looking to build good habits.",
        link: "https://clickup.com/blog/adhd-organization-tools/",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "personal",
        icon: "ReadingLogo"
    },
    { 
        id: 16,
        title: "Changing Habits",
        description: "Information on habit building from UNC at Chapel Hill.",
        link: "https://learningcenter.unc.edu/tips-and-tools/changing-habits/",
        everyone: true,
        diagnoses: false,
        daily: false,
        crisis: false,
        practice: "personal",
        icon: "CalendarLogo"
    },
    { 
        id: 17,
        title: "How to Build Motivation to Overcome Depression",
        description: "Help in finding motivation during a depressive episode.",
        link: "https://learningcenter.unc.edu/tips-and-tools/changing-habits/",
        everyone: false,
        diagnoses: false,
        daily: true,
        crisis: false,
        practice: "personal",
        icon: "AccountLogo"
    }
]